# Generated by Django 4.2.1 on 2023-06-02 17:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_rename_produto_product"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Variacao",
            new_name="Variation",
        ),
    ]
